services:
  sniff-site:
    build:
      context: ./site
    ports:
      - "127.0.0.1:3100:3000"
    networks:
      - pentium
    restart: unless-stopped

networks:
  pentium:
    external: true
    name: pentium_default
